In [92]:
import numpy as np

In [93]:
input = np.array([[8,4,2,3,9,1],[0,6,4,3,7,10],[2,0,1,3,5,8],[6,3,1,4,8,2],[0,2,4,3,5,9],[2,7,9,1,3,5]])
input

array([[ 8,  4,  2,  3,  9,  1],
       [ 0,  6,  4,  3,  7, 10],
       [ 2,  0,  1,  3,  5,  8],
       [ 6,  3,  1,  4,  8,  2],
       [ 0,  2,  4,  3,  5,  9],
       [ 2,  7,  9,  1,  3,  5]])

In [94]:
inputpadded = np.pad(input,1)
inputpadded

array([[ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  8,  4,  2,  3,  9,  1,  0],
       [ 0,  0,  6,  4,  3,  7, 10,  0],
       [ 0,  2,  0,  1,  3,  5,  8,  0],
       [ 0,  6,  3,  1,  4,  8,  2,  0],
       [ 0,  0,  2,  4,  3,  5,  9,  0],
       [ 0,  2,  7,  9,  1,  3,  5,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0]])

In [95]:
len(inputpadded[0])

8

In [96]:
kernel = np.array([[2,0,3],[1,1,0],[3,-1,4]])
kernel

array([[ 2,  0,  3],
       [ 1,  1,  0],
       [ 3, -1,  4]])

In [97]:
len(kernel)

3

In [98]:
test = inputpadded[0:3,0:3]
test

array([[0, 0, 0],
       [0, 8, 4],
       [0, 0, 6]])

In [99]:
result = test*kernel
result

array([[ 0,  0,  0],
       [ 0,  8,  0],
       [ 0,  0, 24]])

In [100]:
result.sum()

32

In [101]:
inputpadded

array([[ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  8,  4,  2,  3,  9,  1,  0],
       [ 0,  0,  6,  4,  3,  7, 10,  0],
       [ 0,  2,  0,  1,  3,  5,  8,  0],
       [ 0,  6,  3,  1,  4,  8,  2,  0],
       [ 0,  0,  2,  4,  3,  5,  9,  0],
       [ 0,  2,  7,  9,  1,  3,  5,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0]])

In [102]:
temp = []

for i in range(len(input)-2):
    for j in range(len(input[0])-2):
        result = input[i:i+len(kernel),j:j+len(kernel)]*kernel
        temp.append(result.sum())
  
conv_matrix =np.array(temp).reshape((4,4))
conv_matrix

array([[38, 38, 58, 55],
       [33, 46, 64, 56],
       [30, 27, 51, 82],
       [52, 40, 71, 42]])

In [89]:
temp = []

for i in range(len(inputpadded)-2):
    for j in range(len(inputpadded[0])-2):
        result = inputpadded[i:i+len(kernel),j:j+len(kernel)]*kernel
        temp.append(result.sum())
  
conv_matrix =np.array(temp).reshape((6,6))
conv_matrix

array([[32, 22, 32, 42, 54, 21],
       [10, 38, 38, 58, 55, 42],
       [26, 33, 46, 64, 56, 49],
       [14, 30, 27, 51, 82, 26],
       [35, 52, 40, 71, 42, 34],
       [ 8, 21, 29, 33, 37, 18]])

In [79]:
test = conv_matrix[0:2,0:2]
test

array([[32, 22],
       [10, 38]])

In [80]:
abs(np.amin(test))

10

In [81]:
np.amax(test)

38

In [82]:
temp = []
poolingsize = 2
stride = 0
for i in range(len(conv_matrix)-1):
    for j in range(len(conv_matrix[0])-1):
        result = conv_matrix[i:i+(poolingsize),j:j+(poolingsize)]
        if abs(np.amin(result)) > np.amax(result):
            temp.append(np.amin(result))
        else:
            temp.append(np.amax(result))
  
pooling_matrix =np.array(temp).reshape((5,5))
pooling_matrix

array([[38, 38, 58, 58, 55],
       [38, 46, 64, 64, 56],
       [33, 46, 64, 82, 82],
       [52, 52, 71, 82, 82],
       [52, 52, 71, 71, 42]])

In [83]:
temp = pooling_matrix[:,[0,2,4]]
pooling_matrixstrided = temp[[0,2,4],:]
pooling_matrixstrided

array([[38, 58, 55],
       [33, 64, 82],
       [52, 71, 42]])